import { createRequire } from "node:module";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { createRustProviderPackage } from "@tsonic/target-rust/provider";
import type { RustProviderPackageImplementation } from "@tsonic/target-rust/provider";
import {
  bufferCarrier,
  cloneOnlyCarrierTraits,
  closedJsValueCarrierTraits,
  cloneDefaultCarrierTraits,
  copyDefaultCarrierTraits,
  hashCarrier,
  hmacCarrier,
  httpIncomingMessageCarrier,
  httpServerCarrier,
  httpServerResponseCarrier,
  makeDirectoryOptionsCarrier,
  processEnvCarrier,
  processMemoryUsageCarrier,
  rmOptionsCarrier,
  searchParamsCarrier,
  statsCarrier,
  timeoutCarrier,
  textDecoderCarrier,
  urlCarrier,
  urlObjectCarrier,
  eventEmitterCarrier,
  readableCarrier,
  writableCarrier,
  readStreamCarrier,
  readStreamOptionsCarrier,
  writeStreamCarrier,
  writeStreamOptionsCarrier,
  fsWatcherCarrier,
  dnsLookupAddressCarrier,
  zlibOptionsCarrier,
  zlibTransformCarrier,
  netSocketCarrier,
  netServerCarrier,
  tlsConnectOptionsCarrier,
  tlsServerOptionsCarrier,
  tlsSocketCarrier,
  tlsServerCarrier,
  httpsServerCarrier,
  httpsClientRequestCarrier,
  readlineOptionsCarrier,
  readlineInterfaceCarrier,
  messageChannelCarrier,
  messagePortCarrier,
  workerCarrier,
  workerOptionsCarrier,
} from "./model.js";
import { assertModule, assertRows } from "./modules/assert.js";
import { bufferModule, bufferRows } from "./modules/buffer.js";
import { cryptoModule, cryptoRows } from "./modules/crypto.js";
import { childProcessModule, childProcessRows } from "./modules/child-process.js";
import { fsModule, fsRows } from "./modules/filesystem.js";
import {
  fsPromisesModule,
  fsPromisesRows,
} from "./modules/filesystem-promises.js";
import { httpModule, httpRows } from "./modules/http.js";
import { osModule, osRows } from "./modules/os.js";
import { pathModule, pathRows } from "./modules/path.js";
import { processModule, processRows } from "./modules/process.js";
import { timersModule, timersRows } from "./modules/timers.js";
import { eventsModule, eventsRows } from "./modules/events.js";
import { streamModule, streamRows } from "./modules/stream.js";
import { urlModule, urlRows } from "./modules/url.js";
import { utilModule, utilRows } from "./modules/util.js";
import {
  dnsModule,
  dnsPromisesModule,
  dnsRows,
} from "./modules/dns.js";
import { zlibModule, zlibRows } from "./modules/zlib.js";
import { netModule, netRows } from "./modules/net.js";
import { tlsModule, tlsRows } from "./modules/tls.js";
import { httpsModule, httpsRows } from "./modules/https.js";
import { readlineModule, readlineRows } from "./modules/readline.js";
import {
  workerThreadCarrierTraits,
  workerThreadsModule,
  workerThreadsRows,
} from "./modules/worker-threads.js";

// Compiled layout is dist/provider/package.js, so the installed package root
// is two directories up from this module.
const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
const require = createRequire(import.meta.url);
const rustJsPackageRoot = dirname(require.resolve("@tsonic/rust-js/package.json"));

export function createRustNodejsProviderPackage(): RustProviderPackageImplementation {
  const providerPackage = createRustProviderPackage({
    id: "@tsonic/rust-nodejs",
    displayName: "Node.js for Rust",
    version: "0.0.1",
    moduleAliases: [
      { moduleSpecifier: "assert", canonicalModuleSpecifier: "node:assert" },
      { moduleSpecifier: "assert/strict", canonicalModuleSpecifier: "node:assert" },
      { moduleSpecifier: "node:assert/strict", canonicalModuleSpecifier: "node:assert" },
      { moduleSpecifier: "buffer", canonicalModuleSpecifier: "node:buffer" },
      { moduleSpecifier: "child_process", canonicalModuleSpecifier: "node:child_process" },
      { moduleSpecifier: "crypto", canonicalModuleSpecifier: "node:crypto" },
      { moduleSpecifier: "fs", canonicalModuleSpecifier: "node:fs" },
      { moduleSpecifier: "fs/promises", canonicalModuleSpecifier: "node:fs/promises" },
      { moduleSpecifier: "http", canonicalModuleSpecifier: "node:http" },
      { moduleSpecifier: "os", canonicalModuleSpecifier: "node:os" },
      { moduleSpecifier: "path", canonicalModuleSpecifier: "node:path" },
      { moduleSpecifier: "process", canonicalModuleSpecifier: "node:process" },
      { moduleSpecifier: "timers", canonicalModuleSpecifier: "node:timers" },
      { moduleSpecifier: "events", canonicalModuleSpecifier: "node:events" },
      { moduleSpecifier: "stream", canonicalModuleSpecifier: "node:stream" },
      { moduleSpecifier: "dns", canonicalModuleSpecifier: "node:dns" },
      { moduleSpecifier: "dns/promises", canonicalModuleSpecifier: "node:dns/promises" },
      { moduleSpecifier: "zlib", canonicalModuleSpecifier: "node:zlib" },
      { moduleSpecifier: "net", canonicalModuleSpecifier: "node:net" },
      { moduleSpecifier: "tls", canonicalModuleSpecifier: "node:tls" },
      { moduleSpecifier: "https", canonicalModuleSpecifier: "node:https" },
      { moduleSpecifier: "readline", canonicalModuleSpecifier: "node:readline" },
      { moduleSpecifier: "worker_threads", canonicalModuleSpecifier: "node:worker_threads" },
      { moduleSpecifier: "util", canonicalModuleSpecifier: "node:util" },
      { moduleSpecifier: "url", canonicalModuleSpecifier: "node:url" },
    ],
    modules: [
      assertModule(),
      pathModule(),
      osModule(),
      fsModule(),
      fsPromisesModule(),
      processModule(),
      bufferModule(),
      childProcessModule(),
      urlModule(),
      cryptoModule(),
      utilModule(),
      httpModule(),
      timersModule(),
      eventsModule(),
      streamModule(),
      dnsModule(),
      dnsPromisesModule(),
      zlibModule(),
      netModule(),
      tlsModule(),
      httpsModule(),
      readlineModule(),
      workerThreadsModule(),
    ],
    types: [
      { exportId: "node:fs::Stats", targetCarrier: statsCarrier },
      {
        exportId: "node:fs::MakeDirectoryOptions",
        targetCarrier: makeDirectoryOptionsCarrier,
        objectLiteralConstruction: { kind: "struct-default" },
      },
      {
        exportId: "node:fs::RmOptions",
        targetCarrier: rmOptionsCarrier,
        objectLiteralConstruction: { kind: "struct-default" },
      },
      { exportId: "node:process::ProcessEnv", targetCarrier: processEnvCarrier },
      { exportId: "node:process::MemoryUsage", targetCarrier: processMemoryUsageCarrier },
      { exportId: "node:process::ProcessWriteStream", targetCarrier: writableCarrier },
      { exportId: "node:buffer::Buffer", targetCarrier: bufferCarrier },
      { exportId: "node:url::URL", targetCarrier: urlCarrier },
      { exportId: "node:url::UrlObject", targetCarrier: urlObjectCarrier },
      { exportId: "node:url::Url", targetCarrier: urlObjectCarrier },
      { exportId: "node:url::UrlWithStringQuery", targetCarrier: urlObjectCarrier },
      { exportId: "node:url::URLSearchParams", targetCarrier: searchParamsCarrier },
      { exportId: "node:crypto::Hash", targetCarrier: hashCarrier },
      { exportId: "node:crypto::Hmac", targetCarrier: hmacCarrier },
      { exportId: "node:http::IncomingMessage", targetCarrier: httpIncomingMessageCarrier },
      { exportId: "node:http::ServerResponse", targetCarrier: httpServerResponseCarrier },
      { exportId: "node:http::Server", targetCarrier: httpServerCarrier },
      { exportId: "node:timers::Timeout", targetCarrier: timeoutCarrier },
      { exportId: "node:util::TextDecoder", targetCarrier: textDecoderCarrier },
      { exportId: "node:events::EventEmitter", targetCarrier: eventEmitterCarrier },
      { exportId: "node:stream::Readable", targetCarrier: readableCarrier },
      { exportId: "node:stream::Writable", targetCarrier: writableCarrier },
      { exportId: "node:fs::ReadStream", targetCarrier: readStreamCarrier },
      { exportId: "node:fs::WriteStream", targetCarrier: writeStreamCarrier },
      {
        exportId: "node:fs::ReadStreamOptions",
        targetCarrier: readStreamOptionsCarrier,
        objectLiteralConstruction: { kind: "struct-default" },
      },
      {
        exportId: "node:fs::WriteStreamOptions",
        targetCarrier: writeStreamOptionsCarrier,
        objectLiteralConstruction: { kind: "struct-default" },
      },
      { exportId: "node:fs::FSWatcher", targetCarrier: fsWatcherCarrier },
      { exportId: "node:dns::LookupAddress", targetCarrier: dnsLookupAddressCarrier },
      {
        exportId: "node:zlib::ZlibOptions",
        targetCarrier: zlibOptionsCarrier,
        objectLiteralConstruction: { kind: "struct-default" },
      },
      { exportId: "node:zlib::Zlib", targetCarrier: zlibTransformCarrier },
      { exportId: "node:net::Socket", targetCarrier: netSocketCarrier },
      { exportId: "node:net::Server", targetCarrier: netServerCarrier },
      {
        exportId: "node:tls::ConnectionOptions",
        targetCarrier: tlsConnectOptionsCarrier,
        objectLiteralConstruction: { kind: "struct-default" },
      },
      {
        exportId: "node:tls::TlsOptions",
        targetCarrier: tlsServerOptionsCarrier,
        objectLiteralConstruction: { kind: "struct-default" },
      },
      { exportId: "node:tls::TLSSocket", targetCarrier: tlsSocketCarrier },
      { exportId: "node:tls::Server", targetCarrier: tlsServerCarrier },
      {
        exportId: "node:https::ServerOptions",
        targetCarrier: tlsServerOptionsCarrier,
        objectLiteralConstruction: { kind: "struct-default" },
      },
      { exportId: "node:https::Server", targetCarrier: httpsServerCarrier },
      { exportId: "node:https::ClientRequest", targetCarrier: httpsClientRequestCarrier },
      {
        exportId: "node:readline::ReadLineOptions",
        targetCarrier: readlineOptionsCarrier,
        objectLiteralConstruction: { kind: "struct-default" },
      },
      { exportId: "node:readline::Interface", targetCarrier: readlineInterfaceCarrier },
      { exportId: "node:worker_threads::Worker", targetCarrier: workerCarrier },
      {
        exportId: "node:worker_threads::WorkerOptions",
        targetCarrier: workerOptionsCarrier,
        objectLiteralConstruction: { kind: "struct-default" },
      },
      { exportId: "node:worker_threads::MessagePort", targetCarrier: messagePortCarrier },
      { exportId: "node:worker_threads::MessageChannel", targetCarrier: messageChannelCarrier },
    ],
    operations: [
      ...assertRows(),
      ...pathRows(),
      ...osRows(),
      ...fsRows(),
      ...fsPromisesRows(),
      ...processRows(),
      ...bufferRows(),
      ...childProcessRows(),
      ...urlRows(),
      ...cryptoRows(),
      ...utilRows(),
      ...httpRows(),
      ...timersRows(),
      ...eventsRows(),
      ...streamRows(),
      ...dnsRows(),
      ...zlibRows(),
      ...netRows(),
      ...tlsRows(),
      ...httpsRows(),
      ...readlineRows(),
      ...workerThreadsRows(),
    ],
    aliasImports: [
      { alias: "node_assert", path: "tsonic_rust_node::assert" },
      { alias: "node_path", path: "tsonic_rust_node::path" },
      { alias: "node_os", path: "tsonic_rust_node::os" },
      { alias: "node_fs", path: "tsonic_rust_node::fs" },
      { alias: "node_fs_promises", path: "tsonic_rust_node::fs_promises" },
      { alias: "node_process", path: "tsonic_rust_node::process" },
      { alias: "node_buffer", path: "tsonic_rust_node::buffer" },
      { alias: "node_child_process", path: "tsonic_rust_node::child_process" },
      { alias: "node_url", path: "tsonic_rust_node::url" },
      { alias: "node_crypto", path: "tsonic_rust_node::crypto" },
      { alias: "node_util", path: "tsonic_rust_node::util" },
      { alias: "node_http", path: "tsonic_rust_node::http" },
      { alias: "node_timers", path: "tsonic_rust_node::timers" },
      { alias: "node_events", path: "tsonic_rust_node::events" },
      { alias: "node_stream", path: "tsonic_rust_node::stream" },
      { alias: "node_dns", path: "tsonic_rust_node::dns" },
      { alias: "node_zlib", path: "tsonic_rust_node::zlib" },
      { alias: "node_net", path: "tsonic_rust_node::net" },
      { alias: "node_tls", path: "tsonic_rust_node::tls" },
      { alias: "node_https", path: "tsonic_rust_node::https" },
      { alias: "node_readline", path: "tsonic_rust_node::readline" },
      { alias: "node_worker_threads", path: "tsonic_rust_node::worker_threads" },
    ],
    carrierPaths: {
      "rust.node.Stats": "tsonic_rust_node::fs::Stats",
      "rust.node.MakeDirectoryOptions": "tsonic_rust_node::fs::MakeDirectoryOptions",
      "rust.node.RmOptions": "tsonic_rust_node::fs::RmOptions",
      "rust.node.Buffer": "tsonic_rust_node::buffer::Buffer",
      "rust.node.SpawnSyncResult": "tsonic_rust_node::child_process::SpawnSyncResult",
      "rust.node.Url": "tsonic_rust_node::url::Url",
      "rust.node.UrlObject": "tsonic_rust_node::url::LegacyUrlObject",
      "rust.node.UrlSearchParams": "tsonic_rust_node::url::UrlSearchParams",
      "rust.node.Hash": "tsonic_rust_node::crypto::Hash",
      "rust.node.Hmac": "tsonic_rust_node::crypto::Hmac",
      "rust.node.ProcessEnv": "tsonic_rust_node::process::ProcessEnv",
      "rust.node.MemoryUsage": "tsonic_rust_node::process::MemoryUsage",
      "rust.node.HttpIncomingMessage": "tsonic_rust_node::http::IncomingMessage",
      "rust.node.HttpServerResponse": "tsonic_rust_node::http::ServerResponseHandle",
      "rust.node.HttpServer": "tsonic_rust_node::http::ServerHandle",
      "rust.node.Timeout": "tsonic_rust_node::timers::Timeout",
      "rust.node.TextDecoder": "tsonic_rust_node::util::TextDecoder",
      "rust.node.EventEmitter": "tsonic_rust_node::events::EventEmitter",
      "rust.node.Readable": "tsonic_rust_node::stream::Readable",
      "rust.node.Writable": "tsonic_rust_node::stream::Writable",
      "rust.node.ReadStream": "tsonic_rust_node::fs::ReadStream",
      "rust.node.WriteStream": "tsonic_rust_node::fs::WriteStream",
      "rust.node.ReadStreamOptions": "tsonic_rust_node::fs::ReadStreamOptions",
      "rust.node.WriteStreamOptions": "tsonic_rust_node::fs::WriteStreamOptions",
      "rust.node.FsWatcher": "tsonic_rust_node::fs::FsWatcher",
      "rust.node.DnsLookupAddress": "tsonic_rust_node::dns::LookupAddress",
      "rust.node.ZlibOptions": "tsonic_rust_node::zlib::SourceZlibOptions",
      "rust.node.ZlibTransform": "tsonic_rust_node::zlib::Zlib",
      "rust.node.NetSocket": "tsonic_rust_node::net::Socket",
      "rust.node.NetServer": "tsonic_rust_node::net::Server",
      "rust.node.TlsConnectOptions": "tsonic_rust_node::tls::SourceConnectOptions",
      "rust.node.TlsServerOptions": "tsonic_rust_node::tls::SourceServerOptions",
      "rust.node.TlsSocket": "tsonic_rust_node::tls::TlsSocket",
      "rust.node.TlsServer": "tsonic_rust_node::tls::TlsServer",
      "rust.node.HttpsServer": "tsonic_rust_node::https::ServerHandle",
      "rust.node.HttpsClientRequest": "tsonic_rust_node::https::ClientRequest",
      "rust.node.ReadlineOptions": "tsonic_rust_node::readline::SourceInterfaceOptions",
      "rust.node.ReadlineInterface": "tsonic_rust_node::readline::Interface",
      "rust.node.Worker": "tsonic_rust_node::worker_threads::Worker",
      "rust.node.WorkerOptions": "tsonic_rust_node::worker_threads::WorkerOptions",
      "rust.node.MessagePort": "tsonic_rust_node::worker_threads::MessagePort",
      "rust.node.MessageChannel": "tsonic_rust_node::worker_threads::MessageChannel",
      "rust.node.NodeError": "tsonic_rust_node::NodeError",
    },
    carrierTraits: {
      "rust.node.Stats": cloneOnlyCarrierTraits,
      "rust.node.MakeDirectoryOptions": copyDefaultCarrierTraits,
      "rust.node.RmOptions": copyDefaultCarrierTraits,
      "rust.node.Buffer": closedJsValueCarrierTraits,
      "rust.node.SpawnSyncResult": cloneOnlyCarrierTraits,
      "rust.node.Url": cloneOnlyCarrierTraits,
      "rust.node.UrlObject": cloneOnlyCarrierTraits,
      "rust.node.UrlSearchParams": cloneOnlyCarrierTraits,
      "rust.node.Hash": cloneOnlyCarrierTraits,
      "rust.node.Hmac": cloneOnlyCarrierTraits,
      "rust.node.MemoryUsage": cloneOnlyCarrierTraits,
      "rust.node.HttpIncomingMessage": cloneOnlyCarrierTraits,
      "rust.node.HttpServerResponse": cloneOnlyCarrierTraits,
      "rust.node.HttpServer": cloneOnlyCarrierTraits,
      "rust.node.Timeout": cloneOnlyCarrierTraits,
      "rust.node.TextDecoder": cloneOnlyCarrierTraits,
      "rust.node.NodeError": cloneOnlyCarrierTraits,
      "rust.node.FsWatcher": cloneOnlyCarrierTraits,
      "rust.node.DnsLookupAddress": cloneOnlyCarrierTraits,
      "rust.node.ZlibOptions": cloneOnlyCarrierTraits,
      "rust.node.TlsConnectOptions": cloneDefaultCarrierTraits,
      "rust.node.TlsServerOptions": cloneDefaultCarrierTraits,
      "rust.node.TlsServer": cloneOnlyCarrierTraits,
      "rust.node.HttpsServer": cloneOnlyCarrierTraits,
      "rust.node.HttpsClientRequest": cloneOnlyCarrierTraits,
      "rust.node.ReadlineOptions": cloneDefaultCarrierTraits,
      "rust.node.Worker": workerThreadCarrierTraits.worker,
      "rust.node.WorkerOptions": workerThreadCarrierTraits.options,
      "rust.node.MessagePort": workerThreadCarrierTraits.port,
    },
    binaryEpilogues: [{
      id: "node-event-loop",
      path: "tsonic_rust_node::run_event_loop",
      requiredCrate: "tsonic_rust_node",
      isFallible: true,
      errorBoundary: "source-program",
    }, {
      id: "node-process-exit-code",
      path: "tsonic_rust_node::process::apply_exit_code",
      requiredCrate: "tsonic_rust_node",
    }],
    crates: [{
      crateName: "tsonic_rust_node",
      cargoPath: resolve(packageRoot, "rust/crates/tsonic_rust_node"),
      registryPatch: "crates-io",
    }],
  });
  const contributeProviderRuntime = providerPackage.runtimeContributions;
  if (contributeProviderRuntime === undefined) {
    throw new Error("The Rust Node provider package did not expose its runtime crate.");
  }
  return Object.freeze({
    ...providerPackage,
    runtimeContributions(
      context: Parameters<NonNullable<RustProviderPackageImplementation["runtimeContributions"]>>[0],
    ) {
      const ownContributions = contributeProviderRuntime(context);
      if (context.selectedSurfaceIds.includes("js")) {
        return ownContributions;
      }
      return Object.freeze({
        ...ownContributions,
        references: Object.freeze([
          ...(ownContributions.references ?? []),
          Object.freeze({
            kind: "cargo-path",
            include: resolve(rustJsPackageRoot, "crates/tsonic_rust_js"),
            attributes: Object.freeze({
              crate: "tsonic_rust_js",
              registryPatch: "crates-io",
              minimumFoundation: "std",
            }),
          }),
        ]),
      });
    },
  });
}
