import { processSignalMembers, processSignalRows, processCarrier } from "./process-signals.js";
import { processArchitectureType, processPlatformType, processMetricExports, processMetricMembers, processMetricRows } from "./process-metrics.js";
import {
  boolCarrier,
  booleanType,
  bufferCarrier,
  float64Carrier,
  fnExport,
  int32Carrier,
  methodMember,
  nullType,
  numberArrayCarrier,
  numberArrayType,
  numberType,
  processEnvCarrier,
  processMemoryUsageCarrier,
  readableCarrier,
  propertyMember,
  providerNativeFallibility,
  providerRef,
  rustOptionTargetType,
  rustUint32ToInt32ValueConversion,
  rustUint64ToFloat64ValueConversion,
  stringArrayCarrier,
  stringArrayType,
  stringCarrier,
  stringType,
  undefinedType,
  unitCarrier,
  valueExport,
  voidType,
  writableCarrier,
} from "../model.js";
import { rustNeverTargetType } from "@tsonic/target-rust/provider";

import type {
  ProviderTypeExpr,
  RustProviderModuleDefinition,
  RustProviderOperationDefinition,
} from "../model.js";
export function processModule(): RustProviderModuleDefinition {
  const m = "node:process";
  const envId = "node:process::ProcessEnv";
  const memoryUsageId = "node:process::MemoryUsage";
  const writeStreamId = "node:process::ProcessWriteStream";
  const defaultId = "node:process::Process";
  const valueExport = (name: string, type: ProviderTypeExpr, documentation?: string) => ({
    id: `${m}::${name}`,
    name,
    kind: "value" as const,
    type,
    ...(documentation === undefined ? {} : { documentation }),
  });
  return {
    moduleSpecifier: m,
    providerModuleId: "tsonic.rust.node.process",
    imports: [{
      moduleSpecifier: "node:buffer",
      namedImports: [{ exportedName: "Buffer" }],
    }, {
      moduleSpecifier: "node:stream",
      namedImports: [{ exportedName: "Readable" }],
    }],
    exports: [
      ...processMetricExports(),
      { id: `${m}::default`, name: "process", kind: "value", exportKind: "default", type: providerRef(m, "Process") },
      {
        id: `${m}::Signals`, name: "Signals", kind: "type",
        type: { kind: "union", types: [
          "SIGABRT", "SIGALRM", "SIGBUS", "SIGCHLD", "SIGCONT", "SIGFPE", "SIGHUP", "SIGILL",
          "SIGINT", "SIGIO", "SIGIOT", "SIGKILL", "SIGPIPE", "SIGPOLL", "SIGPROF", "SIGPWR",
          "SIGQUIT", "SIGSEGV", "SIGSTKFLT", "SIGSTOP", "SIGSYS", "SIGTERM", "SIGTRAP",
          "SIGTSTP", "SIGTTIN", "SIGTTOU", "SIGUNUSED", "SIGURG", "SIGUSR1", "SIGUSR2",
          "SIGVTALRM", "SIGWINCH", "SIGXCPU", "SIGXFSZ", "SIGBREAK", "SIGLOST", "SIGINFO",
        ].map(value => ({ kind: "literal", value })) },
      },
      fnExport(m, "availableMemory", [], numberType),
      fnExport(m, "chdir", [{ name: "directory", type: stringType }], voidType),
      fnExport(m, "constrainedMemory", [], numberType),
      fnExport(m, "cwd", [], stringType),
      {
        id: `${m}::hrtime`,
        name: "hrtime",
        kind: "function",
        signatures: [
          { id: `${m}::hrtime()`, parameters: [], returnType: numberArrayType },
          {
            id: `${m}::hrtime(previous)`,
            parameters: [{ name: "previous", type: numberArrayType }],
            returnType: numberArrayType,
          },
        ],
      },
      fnExport(m, "memoryUsage", [], providerRef(m, "MemoryUsage")),
      fnExport(m, "uptime", [], numberType),
      {
        id: envId,
        name: "ProcessEnv",
        kind: "interface" as const,
        members: [{
          id: `${envId}.indexer`,
          name: "indexer",
          kind: "indexer" as const,
          signatures: [{
            id: `${envId}.indexer(name)`,
            parameters: [{ name: "name", type: stringType }],
            returnType: { kind: "union", types: [stringType, undefinedType] },
          }],
        }],
      },
      {
        id: memoryUsageId,
        name: "MemoryUsage",
        kind: "class",
        members: [
          propertyMember(memoryUsageId, "rss", numberType),
          propertyMember(memoryUsageId, "heapTotal", numberType),
          propertyMember(memoryUsageId, "heapUsed", numberType),
          propertyMember(memoryUsageId, "external", numberType),
          propertyMember(memoryUsageId, "arrayBuffers", numberType),
        ],
      },
      {
        id: writeStreamId,
        name: "ProcessWriteStream",
        kind: "class",
        members: [
          {
            id: `${writeStreamId}.write`,
            name: "write",
            kind: "method",
            signatures: [
              {
                id: `${writeStreamId}.write(string)`,
                parameters: [{ name: "chunk", type: stringType }],
                returnType: booleanType,
              },
              {
                id: `${writeStreamId}.write(buffer)`,
                parameters: [{ name: "chunk", type: providerRef("node:buffer", "Buffer") }],
                returnType: booleanType,
              },
            ],
          },
          propertyMember(writeStreamId, "isTTY", booleanType),
          propertyMember(writeStreamId, "fd", numberType),
        ],
      },
      valueExport("env", providerRef(m, "ProcessEnv")),
      valueExport("stdout", providerRef(m, "ProcessWriteStream")),
      valueExport("stderr", providerRef(m, "ProcessWriteStream")),
      valueExport("stdin", providerRef("node:stream", "Readable")),
      valueExport("platform", processPlatformType),
      valueExport("arch", processArchitectureType),
      valueExport("execArgv", stringArrayType),
      valueExport("argv", stringArrayType),
      valueExport("argv0", stringType),
      valueExport("pid", numberType),
      valueExport("ppid", numberType),
      valueExport("execPath", stringType),
      valueExport("exitCode", { kind: "union", types: [numberType, nullType] }),
      valueExport("version", stringType),
      fnExport(m, "exit", [{ name: "code", type: numberType }], { kind: "never" }),
      {
        id: defaultId,
        name: "Process",
        kind: "interface",
        members: [
          ...processMetricMembers(),
          ...processSignalMembers(),
          methodMember(defaultId, "availableMemory", [], numberType),
          methodMember(defaultId, "chdir", [{ name: "directory", type: stringType }], voidType),
          methodMember(defaultId, "constrainedMemory", [], numberType),
          methodMember(defaultId, "cwd", [], stringType),
          {
            id: `${defaultId}.hrtime`,
            name: "hrtime",
            kind: "method",
            signatures: [
              { id: `${defaultId}.hrtime()`, parameters: [], returnType: numberArrayType },
              {
                id: `${defaultId}.hrtime(previous)`,
                parameters: [{ name: "previous", type: numberArrayType }],
                returnType: numberArrayType,
              },
            ],
          },
          methodMember(defaultId, "memoryUsage", [], providerRef(m, "MemoryUsage")),
          methodMember(defaultId, "uptime", [], numberType),
          propertyMember(defaultId, "env", providerRef(m, "ProcessEnv")),
          propertyMember(defaultId, "stdout", providerRef(m, "ProcessWriteStream")),
          propertyMember(defaultId, "stderr", providerRef(m, "ProcessWriteStream")),
          propertyMember(defaultId, "stdin", providerRef("node:stream", "Readable")),
          propertyMember(defaultId, "platform", processPlatformType),
          propertyMember(defaultId, "arch", processArchitectureType),
          propertyMember(defaultId, "execArgv", stringArrayType),
          propertyMember(defaultId, "argv", stringArrayType),
          propertyMember(defaultId, "argv0", stringType),
          propertyMember(defaultId, "pid", numberType),
          propertyMember(defaultId, "ppid", numberType),
          propertyMember(defaultId, "execPath", stringType),
          propertyMember(defaultId, "version", stringType),
          propertyMember(defaultId, "exitCode", { kind: "union", types: [numberType, nullType] }, {
            readonly: false,
          }),
          methodMember(defaultId, "exit", [{ name: "code", type: numberType }], { kind: "never" }),
        ],
      },
    ],
  };
}

export function processRows(): readonly RustProviderOperationDefinition[] {
  const m = "node:process";
  const defaultId = "node:process::Process";
  const memoryUsageId = `${m}::MemoryUsage`;
  const writeStreamId = `${m}::ProcessWriteStream`;
  return [
    ...processMetricRows(),
    ...processSignalRows(),
    { exportId: `${m}::default`, operationKind: "property", target: { form: "call", path: "node_process::process" }, resultCarrier: processCarrier },
    { exportId: `${m}::execArgv`, operationKind: "property", target: { form: "call", path: "node_process::exec_argv" }, resultCarrier: stringArrayCarrier },
    { exportId: defaultId, memberId: `${defaultId}.execArgv`, operationKind: "property", target: { form: "call", path: "node_process::exec_argv" }, resultCarrier: stringArrayCarrier },
    { exportId: `${m}::availableMemory`, operationKind: "method", target: { form: "call", path: "node_process::available_memory" }, resultCarrier: float64Carrier, resultConversion: rustUint64ToFloat64ValueConversion },
    { exportId: `${m}::chdir`, operationKind: "method", target: { form: "call", path: "node_process::chdir", argModes: ["ref"] }, resultCarrier: unitCarrier, parameterCarriers: [stringCarrier], ...providerNativeFallibility },
    { exportId: `${m}::constrainedMemory`, operationKind: "method", target: { form: "call", path: "node_process::constrained_memory" }, resultCarrier: float64Carrier, resultConversion: rustUint64ToFloat64ValueConversion },
    { exportId: `${m}::cwd`, operationKind: "method", target: { form: "call", path: "node_process::cwd" }, resultCarrier: stringCarrier, ...providerNativeFallibility },
    { exportId: `${m}::hrtime`, signatureId: `${m}::hrtime()`, operationKind: "method", target: { form: "call", path: "node_process::hrtime_open_number" }, resultCarrier: numberArrayCarrier },
    { exportId: `${m}::hrtime`, signatureId: `${m}::hrtime(previous)`, operationKind: "method", target: { form: "call", path: "node_process::hrtime_since_number", argModes: ["ref"] }, resultCarrier: numberArrayCarrier, parameterCarriers: [numberArrayCarrier], ...providerNativeFallibility },
    { exportId: `${m}::memoryUsage`, operationKind: "method", target: { form: "call", path: "node_process::memory_usage" }, resultCarrier: processMemoryUsageCarrier },
    { exportId: `${m}::uptime`, operationKind: "method", target: { form: "call", path: "node_process::uptime" }, resultCarrier: float64Carrier },
    { exportId: `${m}::platform`, operationKind: "property", target: { form: "call", path: "node_process::platform" }, resultCarrier: stringCarrier },
    { exportId: `${m}::arch`, operationKind: "property", target: { form: "call", path: "node_process::arch" }, resultCarrier: stringCarrier },
    { exportId: `${m}::argv`, operationKind: "property", target: { form: "call", path: "node_process::argv" }, resultCarrier: stringArrayCarrier, ...providerNativeFallibility },
    { exportId: `${m}::argv0`, operationKind: "property", target: { form: "call", path: "node_process::argv0" }, resultCarrier: stringCarrier },
    { exportId: `${m}::pid`, operationKind: "property", target: { form: "call", path: "node_process::pid" }, resultCarrier: int32Carrier, resultConversion: rustUint32ToInt32ValueConversion },
    { exportId: `${m}::ppid`, operationKind: "property", target: { form: "call", path: "node_process::ppid" }, resultCarrier: int32Carrier, resultConversion: rustUint32ToInt32ValueConversion },
    { exportId: `${m}::env`, operationKind: "property", target: { form: "call", path: "node_process::environment" }, resultCarrier: processEnvCarrier },
    { exportId: `${m}::stdout`, operationKind: "property", target: { form: "call", path: "node_process::stdout" }, resultCarrier: writableCarrier },
    { exportId: `${m}::stderr`, operationKind: "property", target: { form: "call", path: "node_process::stderr" }, resultCarrier: writableCarrier },
    { exportId: `${m}::stdin`, operationKind: "property", target: { form: "call", path: "node_process::stdin" }, resultCarrier: readableCarrier },
    { exportId: `${m}::execPath`, operationKind: "property", target: { form: "call", path: "node_process::exec_path" }, resultCarrier: stringCarrier, ...providerNativeFallibility },
    { exportId: `${m}::exitCode`, operationKind: "property", target: { form: "call", path: "node_process::exit_code" }, resultCarrier: rustOptionTargetType(int32Carrier) },
    { exportId: `${m}::exitCode`, operationKind: "property-set", target: { form: "call", path: "node_process::set_exit_code" }, resultCarrier: unitCarrier, parameterCarriers: [rustOptionTargetType(int32Carrier)] },
    { exportId: `${m}::version`, operationKind: "property", target: { form: "call", path: "node_process::version" }, resultCarrier: stringCarrier },
    { exportId: `${m}::ProcessEnv`, memberId: `${m}::ProcessEnv.indexer`, operationKind: "indexer", target: { form: "receiver-method", name: "get", argModes: ["ref"] }, receiverCarrier: processEnvCarrier, resultCarrier: rustOptionTargetType(stringCarrier), parameterCarriers: [stringCarrier] },
    { exportId: `${m}::ProcessEnv`, memberId: `${m}::ProcessEnv.indexer`, operationKind: "index-set", target: { form: "receiver-method", name: "set", argModes: ["ref", "value"] }, receiverCarrier: processEnvCarrier, resultCarrier: unitCarrier, parameterCarriers: [stringCarrier, rustOptionTargetType(stringCarrier)], ...providerNativeFallibility },
    { exportId: memoryUsageId, memberId: `${memoryUsageId}.rss`, operationKind: "property", target: { form: "field", name: "rss" }, resultCarrier: float64Carrier, resultConversion: rustUint64ToFloat64ValueConversion },
    { exportId: memoryUsageId, memberId: `${memoryUsageId}.heapTotal`, operationKind: "property", target: { form: "field", name: "heap_total" }, resultCarrier: float64Carrier, resultConversion: rustUint64ToFloat64ValueConversion },
    { exportId: memoryUsageId, memberId: `${memoryUsageId}.heapUsed`, operationKind: "property", target: { form: "field", name: "heap_used" }, resultCarrier: float64Carrier, resultConversion: rustUint64ToFloat64ValueConversion },
    { exportId: memoryUsageId, memberId: `${memoryUsageId}.external`, operationKind: "property", target: { form: "field", name: "external" }, resultCarrier: float64Carrier, resultConversion: rustUint64ToFloat64ValueConversion },
    { exportId: memoryUsageId, memberId: `${memoryUsageId}.arrayBuffers`, operationKind: "property", target: { form: "field", name: "array_buffers" }, resultCarrier: float64Carrier, resultConversion: rustUint64ToFloat64ValueConversion },
    { exportId: writeStreamId, memberId: `${writeStreamId}.write`, signatureId: `${writeStreamId}.write(string)`, operationKind: "method", target: { form: "receiver-method", name: "write_string", argModes: ["ref"], mutatesReceiver: true }, resultCarrier: boolCarrier, receiverCarrier: writableCarrier, parameterCarriers: [stringCarrier], ...providerNativeFallibility },
    { exportId: writeStreamId, memberId: `${writeStreamId}.write`, signatureId: `${writeStreamId}.write(buffer)`, operationKind: "method", target: { form: "receiver-method", name: "write_buffer", argModes: ["ref"], mutatesReceiver: true }, resultCarrier: boolCarrier, receiverCarrier: writableCarrier, parameterCarriers: [bufferCarrier], ...providerNativeFallibility },
    { exportId: writeStreamId, memberId: `${writeStreamId}.isTTY`, operationKind: "property", target: { form: "receiver-method", name: "is_tty" }, resultCarrier: boolCarrier, receiverCarrier: writableCarrier },
    { exportId: writeStreamId, memberId: `${writeStreamId}.fd`, operationKind: "property", target: { form: "receiver-method", name: "fd" }, resultCarrier: int32Carrier, receiverCarrier: writableCarrier },
    { exportId: `${m}::exit`, operationKind: "method", target: { form: "call", path: "std::process::exit" }, resultCarrier: rustNeverTargetType(), parameterCarriers: [int32Carrier] },
    { exportId: defaultId, memberId: `${defaultId}.availableMemory`, signatureId: `${defaultId}.availableMemory()`, operationKind: "method", target: { form: "call", path: "node_process::available_memory" }, resultCarrier: float64Carrier, resultConversion: rustUint64ToFloat64ValueConversion },
    { exportId: defaultId, memberId: `${defaultId}.chdir`, signatureId: `${defaultId}.chdir(directory)`, operationKind: "method", target: { form: "call", path: "node_process::chdir", argModes: ["ref"] }, resultCarrier: unitCarrier, parameterCarriers: [stringCarrier], ...providerNativeFallibility },
    { exportId: defaultId, memberId: `${defaultId}.constrainedMemory`, signatureId: `${defaultId}.constrainedMemory()`, operationKind: "method", target: { form: "call", path: "node_process::constrained_memory" }, resultCarrier: float64Carrier, resultConversion: rustUint64ToFloat64ValueConversion },
    { exportId: defaultId, memberId: `${defaultId}.cwd`, signatureId: `${defaultId}.cwd()`, operationKind: "method", target: { form: "call", path: "node_process::cwd" }, resultCarrier: stringCarrier, ...providerNativeFallibility },
    { exportId: defaultId, memberId: `${defaultId}.hrtime`, signatureId: `${defaultId}.hrtime()`, operationKind: "method", target: { form: "call", path: "node_process::hrtime_open_number" }, resultCarrier: numberArrayCarrier },
    { exportId: defaultId, memberId: `${defaultId}.hrtime`, signatureId: `${defaultId}.hrtime(previous)`, operationKind: "method", target: { form: "call", path: "node_process::hrtime_since_number", argModes: ["ref"] }, resultCarrier: numberArrayCarrier, parameterCarriers: [numberArrayCarrier], ...providerNativeFallibility },
    { exportId: defaultId, memberId: `${defaultId}.memoryUsage`, signatureId: `${defaultId}.memoryUsage()`, operationKind: "method", target: { form: "call", path: "node_process::memory_usage" }, resultCarrier: processMemoryUsageCarrier },
    { exportId: defaultId, memberId: `${defaultId}.uptime`, signatureId: `${defaultId}.uptime()`, operationKind: "method", target: { form: "call", path: "node_process::uptime" }, resultCarrier: float64Carrier },
    { exportId: defaultId, memberId: `${defaultId}.platform`, operationKind: "property", target: { form: "call", path: "node_process::platform" }, resultCarrier: stringCarrier },
    { exportId: defaultId, memberId: `${defaultId}.arch`, operationKind: "property", target: { form: "call", path: "node_process::arch" }, resultCarrier: stringCarrier },
    { exportId: defaultId, memberId: `${defaultId}.argv`, operationKind: "property", target: { form: "call", path: "node_process::argv" }, resultCarrier: stringArrayCarrier, ...providerNativeFallibility },
    { exportId: defaultId, memberId: `${defaultId}.argv0`, operationKind: "property", target: { form: "call", path: "node_process::argv0" }, resultCarrier: stringCarrier },
    { exportId: defaultId, memberId: `${defaultId}.pid`, operationKind: "property", target: { form: "call", path: "node_process::pid" }, resultCarrier: int32Carrier, resultConversion: rustUint32ToInt32ValueConversion },
    { exportId: defaultId, memberId: `${defaultId}.ppid`, operationKind: "property", target: { form: "call", path: "node_process::ppid" }, resultCarrier: int32Carrier, resultConversion: rustUint32ToInt32ValueConversion },
    { exportId: defaultId, memberId: `${defaultId}.env`, operationKind: "property", target: { form: "call", path: "node_process::environment" }, resultCarrier: processEnvCarrier },
    { exportId: defaultId, memberId: `${defaultId}.stdout`, operationKind: "property", target: { form: "call", path: "node_process::stdout" }, resultCarrier: writableCarrier },
    { exportId: defaultId, memberId: `${defaultId}.stderr`, operationKind: "property", target: { form: "call", path: "node_process::stderr" }, resultCarrier: writableCarrier },
    { exportId: defaultId, memberId: `${defaultId}.stdin`, operationKind: "property", target: { form: "call", path: "node_process::stdin" }, resultCarrier: readableCarrier },
    { exportId: defaultId, memberId: `${defaultId}.execPath`, operationKind: "property", target: { form: "call", path: "node_process::exec_path" }, resultCarrier: stringCarrier, ...providerNativeFallibility },
    { exportId: defaultId, memberId: `${defaultId}.exitCode`, operationKind: "property", target: { form: "call", path: "node_process::exit_code" }, resultCarrier: rustOptionTargetType(int32Carrier) },
    { exportId: defaultId, memberId: `${defaultId}.exitCode`, operationKind: "property-set", target: { form: "call", path: "node_process::set_exit_code" }, resultCarrier: unitCarrier, parameterCarriers: [rustOptionTargetType(int32Carrier)] },
    { exportId: defaultId, memberId: `${defaultId}.version`, operationKind: "property", target: { form: "call", path: "node_process::version" }, resultCarrier: stringCarrier },
    { exportId: defaultId, memberId: `${defaultId}.exit`, signatureId: `${defaultId}.exit(code)`, operationKind: "method", target: { form: "call", path: "std::process::exit" }, resultCarrier: rustNeverTargetType(), parameterCarriers: [int32Carrier] },
  ];
}

// --- node:buffer -------------------------------------------------------------
